name: Build and Deploy to WordPress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Cache Minecraft JARs
      uses: actions/cache@v4
      with:
        path: .cache/jars
        key: ${{ runner.os }}-minecraft-jars-${{ hashFiles('cli/versions.json') }}
        restore-keys: |
          ${{ runner.os }}-minecraft-jars-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build widget
      run: |
        npm run fetch-jars
        npm run extract-assets
        npm run build-data
        npm run build-icons
        npm run pack-data
        npm run build-widget
    
    - name: Upload widget artifact
      uses: actions/upload-artifact@v4
      with:
        name: minecraft-widget
        path: |
          dist/minecraft-craft-widget.min.js
          out/icons/**/*.png
    
    - name: Create Plugin Package
      run: |
        node scripts/create-plugin-zip.js
    
    - name: Deploy to WordPress
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        WORDPRESS_MEDIA_FOLDER: ${{ secrets.WORDPRESS_MEDIA_FOLDER }}
      run: |
        echo "Note: Direct JS upload may be blocked by WordPress."
        echo "The widget has been packaged as a plugin instead."
        echo ""
        echo "Plugin file created: dist/minecraft-craft-widget-plugin.zip"
        echo ""
        echo "To use the widget:"
        echo "1. Download the plugin from GitHub releases"
        echo "2. Upload to WordPress: Plugins → Add New → Upload"
        echo "3. Activate the plugin"
        echo "4. Use shortcode: [minecraft_widget]"
        
        # Try deployment anyway, but don't fail if it doesn't work
        node scripts/deploy-to-wordpress.js || true
    
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Build ${{ github.run_number }}
        generate_release_notes: false
        draft: false
        prerelease: false
        files: |
          dist/minecraft-craft-widget.min.js
          dist/minecraft-craft-widget-plugin.zip
          dist/embed-snippet.html
        body: |
          Automated build of Minecraft Craft Widget.
          
          ## Installation Options
          
          ### Option 1: WordPress Plugin (Recommended)
          1. Download `minecraft-craft-widget-plugin.zip`
          2. Upload via WordPress Admin → Plugins → Add New → Upload
          3. Activate the plugin
          4. Use shortcode: `[minecraft_widget]`
          
          ### Option 2: Direct Embed
          ```html
          <div id="mc-craft"></div>
          <script src="/path/to/minecraft-craft-widget.min.js"></script>
          ```
          
          Note: Some WordPress installations block .js uploads. Use the plugin method if direct upload fails.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}